<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5KR3QEN" failures="2" tests="9" name="RetryMultipleFailedTestCases" time="0.107" errors="0" timestamp="2021-12-08T01:14:00 IST">
  <testcase classname="TestCases.MyTest1" name="Test1" time="0.012">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestCases.MyTest1" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestCases.MyTest1" name="Test1" time="0.002">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="TestCases.MyTest1" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestCases.MyTest1.Test1(MyTest1.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="TestCases.MyTest1" name="Test2" time="0.002">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestCases.MyTest1" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestCases.MyTest1" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="TestCases.MyTest1" name="Test2" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestCases.MyTest1.Test2(MyTest1.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase classname="TestCases.MyTest1" name="Test3" time="0.002"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
